# This workflow will build the source code and create a new github package.
# For more information see: https://github.com/marketplace/actions/build-and-push-docker-images

name: Build

on:
  push:
    branches:
      - master
      - develop
      - release/*
    tags:
      - v*
  pull_request:
    branches:
      - master
      - develop
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest
    container: node:12-alpine
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install
    
    - name: Unit Test
      run: npm test

    - name: Build the package
      run: npm run build

    - name: Remove node_modules
      run: rm -rf node_modules

    - name: Install production dependencies
      run: npm install --production
